# Generated by Django 4.2.26 on 2025-11-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prioridad', models.CharField(choices=[('A', 'A'), ('M', 'M'), ('B', 'B')], default='M', max_length=1)),
                ('nota', models.TextField(blank=True, null=True)),
                ('comprado', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_comprado', models.DateTimeField(blank=True, null=True)),
                ('cantidad_comprada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('SOBRE_PRESUPUESTO', 'SOBRE_PRESUPUESTO')], default='OK', max_length=20)),
                ('alerta_activa', models.CharField(choices=[('NINGUNA', 'NINGUNA'), ('AMARILLA', 'AMARILLA'), ('ROJA', 'ROJA')], default='NINGUNA', max_length=10)),
                ('alerta_ultima_vista_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'listas',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios_json', models.TextField(blank=True, null=True)),
                ('total_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('presupuesto_no_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='smartcar_app.lista')),
            ],
            options={
                'db_table': 'recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('moneda_preferida', models.CharField(blank=True, max_length=3, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='PreferenciasAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=False)),
                ('badge', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_alertas', to='smartcar_app.usuario')),
            ],
            options={
                'db_table': 'preferencias_alertas',
            },
        ),
        migrations.CreateModel(
            name='PrecioOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=100)),
                ('precio_consultado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_online', to='smartcar_app.item')),
            ],
            options={
                'db_table': 'precios_online',
            },
        ),
        migrations.AddField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='smartcar_app.usuario'),
        ),
        migrations.AddField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smartcar_app.lista'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_items', models.IntegerField(default=0)),
                ('promedio_por_categoria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='smartcar_app.usuario')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('entidad', models.CharField(blank=True, max_length=40, null=True)),
                ('entidad_id', models.IntegerField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='smartcar_app.usuario')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(max_length=255)),
                ('plataforma', models.CharField(choices=[('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('WEB', 'WEB')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='smartcar_app.usuario')),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tienda', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='smartcar_app.item')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARILLA', 'AMARILLA'), ('ROJA', 'ROJA')], max_length=10)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_al_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='smartcar_app.lista')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_recomendaciones', to='smartcar_app.item')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_recomendados', to='smartcar_app.recomendacion')),
            ],
            options={
                'db_table': 'recomendacion_items',
                'unique_together': {('recomendacion', 'item')},
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('lista', 'nombre'), name='uq_item_nombre_por_lista'),
        ),
    ]
